/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GiaHan service. Represents a row in the &quot;giahan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thuvien.model.impl.GiaHanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thuvien.model.impl.GiaHanImpl}.
 * </p>
 *
 * @author ADMIN
 * @see GiaHan
 * @see com.thuvien.model.impl.GiaHanImpl
 * @see com.thuvien.model.impl.GiaHanModelImpl
 * @generated
 */
public interface GiaHanModel extends BaseModel<GiaHan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gia han model instance should use the {@link GiaHan} interface instead.
	 */

	/**
	 * Returns the primary key of this gia han.
	 *
	 * @return the primary key of this gia han
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gia han.
	 *
	 * @param primaryKey the primary key of this gia han
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id gh of this gia han.
	 *
	 * @return the id gh of this gia han
	 */
	public long getIdGh();

	/**
	 * Sets the id gh of this gia han.
	 *
	 * @param IdGh the id gh of this gia han
	 */
	public void setIdGh(long IdGh);

	/**
	 * Returns the ngay gian han of this gia han.
	 *
	 * @return the ngay gian han of this gia han
	 */
	public Date getNgayGianHan();

	/**
	 * Sets the ngay gian han of this gia han.
	 *
	 * @param NgayGianHan the ngay gian han of this gia han
	 */
	public void setNgayGianHan(Date NgayGianHan);

	/**
	 * Returns the phieu muon ID of this gia han.
	 *
	 * @return the phieu muon ID of this gia han
	 */
	public long getPhieuMuonId();

	/**
	 * Sets the phieu muon ID of this gia han.
	 *
	 * @param PhieuMuonId the phieu muon ID of this gia han
	 */
	public void setPhieuMuonId(long PhieuMuonId);

	/**
	 * Returns the trang thai of this gia han.
	 *
	 * @return the trang thai of this gia han
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this gia han.
	 *
	 * @param TrangThai the trang thai of this gia han
	 */
	public void setTrangThai(String TrangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.thuvien.model.GiaHan giaHan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.thuvien.model.GiaHan> toCacheModel();

	@Override
	public com.thuvien.model.GiaHan toEscapedModel();

	@Override
	public com.thuvien.model.GiaHan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}