/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PhuongThanhPho service. Represents a row in the &quot;phuongthanhpho&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thuvien.model.impl.PhuongThanhPhoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thuvien.model.impl.PhuongThanhPhoImpl}.
 * </p>
 *
 * @author ADMIN
 * @see PhuongThanhPho
 * @see com.thuvien.model.impl.PhuongThanhPhoImpl
 * @see com.thuvien.model.impl.PhuongThanhPhoModelImpl
 * @generated
 */
public interface PhuongThanhPhoModel extends BaseModel<PhuongThanhPho> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phuong thanh pho model instance should use the {@link PhuongThanhPho} interface instead.
	 */

	/**
	 * Returns the primary key of this phuong thanh pho.
	 *
	 * @return the primary key of this phuong thanh pho
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phuong thanh pho.
	 *
	 * @param primaryKey the primary key of this phuong thanh pho
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the name of this phuong thanh pho.
	 *
	 * @return the name of this phuong thanh pho
	 */
	public long getName();

	/**
	 * Sets the name of this phuong thanh pho.
	 *
	 * @param name the name of this phuong thanh pho
	 */
	public void setName(long name);

	/**
	 * Returns the type of this phuong thanh pho.
	 *
	 * @return the type of this phuong thanh pho
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this phuong thanh pho.
	 *
	 * @param Type the type of this phuong thanh pho
	 */
	public void setType(String Type);

	/**
	 * Returns the quan thanh pho ID of this phuong thanh pho.
	 *
	 * @return the quan thanh pho ID of this phuong thanh pho
	 */
	@AutoEscape
	public String getQuanThanhPhoId();

	/**
	 * Sets the quan thanh pho ID of this phuong thanh pho.
	 *
	 * @param QuanThanhPhoId the quan thanh pho ID of this phuong thanh pho
	 */
	public void setQuanThanhPhoId(String QuanThanhPhoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.thuvien.model.PhuongThanhPho phuongThanhPho);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.thuvien.model.PhuongThanhPho> toCacheModel();

	@Override
	public com.thuvien.model.PhuongThanhPho toEscapedModel();

	@Override
	public com.thuvien.model.PhuongThanhPho toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}