/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Sach service. Represents a row in the &quot;sach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thuvien.model.impl.SachModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thuvien.model.impl.SachImpl}.
 * </p>
 *
 * @author ADMIN
 * @see Sach
 * @see com.thuvien.model.impl.SachImpl
 * @see com.thuvien.model.impl.SachModelImpl
 * @generated
 */
public interface SachModel extends BaseModel<Sach> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sach model instance should use the {@link Sach} interface instead.
	 */

	/**
	 * Returns the primary key of this sach.
	 *
	 * @return the primary key of this sach
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sach.
	 *
	 * @param primaryKey the primary key of this sach
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this sach.
	 *
	 * @return the ID of this sach
	 */
	public long getId();

	/**
	 * Sets the ID of this sach.
	 *
	 * @param Id the ID of this sach
	 */
	public void setId(long Id);

	/**
	 * Returns the ten sach of this sach.
	 *
	 * @return the ten sach of this sach
	 */
	@AutoEscape
	public String getTenSach();

	/**
	 * Sets the ten sach of this sach.
	 *
	 * @param TenSach the ten sach of this sach
	 */
	public void setTenSach(String TenSach);

	/**
	 * Returns the the loai ID of this sach.
	 *
	 * @return the the loai ID of this sach
	 */
	public long getTheLoaiId();

	/**
	 * Sets the the loai ID of this sach.
	 *
	 * @param TheLoaiId the the loai ID of this sach
	 */
	public void setTheLoaiId(long TheLoaiId);

	/**
	 * Returns the so luong of this sach.
	 *
	 * @return the so luong of this sach
	 */
	public long getSoLuong();

	/**
	 * Sets the so luong of this sach.
	 *
	 * @param SoLuong the so luong of this sach
	 */
	public void setSoLuong(long SoLuong);

	/**
	 * Returns the trang thai of this sach.
	 *
	 * @return the trang thai of this sach
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this sach.
	 *
	 * @param TrangThai the trang thai of this sach
	 */
	public void setTrangThai(String TrangThai);

	/**
	 * Returns the nha x b of this sach.
	 *
	 * @return the nha x b of this sach
	 */
	@AutoEscape
	public String getNhaXB();

	/**
	 * Sets the nha x b of this sach.
	 *
	 * @param NhaXB the nha x b of this sach
	 */
	public void setNhaXB(String NhaXB);

	/**
	 * Returns the ma sach of this sach.
	 *
	 * @return the ma sach of this sach
	 */
	@AutoEscape
	public String getMaSach();

	/**
	 * Sets the ma sach of this sach.
	 *
	 * @param MaSach the ma sach of this sach
	 */
	public void setMaSach(String MaSach);

	/**
	 * Returns the ke of this sach.
	 *
	 * @return the ke of this sach
	 */
	@AutoEscape
	public String getKe();

	/**
	 * Sets the ke of this sach.
	 *
	 * @param Ke the ke of this sach
	 */
	public void setKe(String Ke);

	/**
	 * Returns the tang of this sach.
	 *
	 * @return the tang of this sach
	 */
	@AutoEscape
	public String getTang();

	/**
	 * Sets the tang of this sach.
	 *
	 * @param Tang the tang of this sach
	 */
	public void setTang(String Tang);

	/**
	 * Returns the mota of this sach.
	 *
	 * @return the mota of this sach
	 */
	@AutoEscape
	public String getMota();

	/**
	 * Sets the mota of this sach.
	 *
	 * @param Mota the mota of this sach
	 */
	public void setMota(String Mota);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.thuvien.model.Sach sach);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.thuvien.model.Sach> toCacheModel();

	@Override
	public com.thuvien.model.Sach toEscapedModel();

	@Override
	public com.thuvien.model.Sach toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}