/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.thuvien.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TheLoai service. Represents a row in the &quot;theloai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.thuvien.model.impl.TheLoaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.thuvien.model.impl.TheLoaiImpl}.
 * </p>
 *
 * @author ADMIN
 * @see TheLoai
 * @see com.thuvien.model.impl.TheLoaiImpl
 * @see com.thuvien.model.impl.TheLoaiModelImpl
 * @generated
 */
public interface TheLoaiModel extends BaseModel<TheLoai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a the loai model instance should use the {@link TheLoai} interface instead.
	 */

	/**
	 * Returns the primary key of this the loai.
	 *
	 * @return the primary key of this the loai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this the loai.
	 *
	 * @param primaryKey the primary key of this the loai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this the loai.
	 *
	 * @return the ID of this the loai
	 */
	public long getId();

	/**
	 * Sets the ID of this the loai.
	 *
	 * @param Id the ID of this the loai
	 */
	public void setId(long Id);

	/**
	 * Returns the ten the loai of this the loai.
	 *
	 * @return the ten the loai of this the loai
	 */
	@AutoEscape
	public String getTenTheLoai();

	/**
	 * Sets the ten the loai of this the loai.
	 *
	 * @param TenTheLoai the ten the loai of this the loai
	 */
	public void setTenTheLoai(String TenTheLoai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.thuvien.model.TheLoai theLoai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.thuvien.model.TheLoai> toCacheModel();

	@Override
	public com.thuvien.model.TheLoai toEscapedModel();

	@Override
	public com.thuvien.model.TheLoai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}